name = "AWSBraket"
uuid = "f5a38104-9b45-4271-a786-09a83c4f15bf"
authors = ["Roger-luo <rogerluo.rl18@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
